# Generated by Django 5.2.8 on 2026-08-25 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('headline', models.CharField(blank=True, default='', max_length=200, verbose_name='Section headline')),
                ('summary', models.TextField(blank=True, default='', help_text='One or two paragraphs introducing the school.')),
                ('history', models.TextField(blank=True, default='')),
                ('mission', models.TextField(blank=True, default='')),
                ('vision', models.TextField(blank=True, default='')),
                ('motto', models.CharField(blank=True, default='', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website/about/')),
            ],
            options={
                'verbose_name': 'About the school',
                'verbose_name_plural': 'About the school',
                'db_table': 'about_section',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('year', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('metric', models.CharField(blank=True, default='', help_text='A number worth showing large, e.g. "100%" or "42".', max_length=60)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'school_achievements',
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(blank=True, default='', help_text='Headline drawn over the image.', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('caption', models.CharField(blank=True, default='', help_text='Small eyebrow label above the title.', max_length=120)),
                ('image', models.ImageField(upload_to='website/hero/')),
                ('alt_text', models.CharField(blank=True, default='', help_text='Described for screen readers; falls back to the title.', max_length=200)),
                ('link_url', models.CharField(blank=True, default='', help_text='Optional call-to-action target.', max_length=300)),
                ('link_label', models.CharField(blank=True, default='', max_length=60)),
                ('order', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Lower numbers appear first.')),
            ],
            options={
                'verbose_name': 'Hero slide',
                'db_table': 'hero_slides',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuccessfulStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('academic_year', models.CharField(db_index=True, help_text='e.g. "2025"', max_length=10)),
                ('full_name', models.CharField(max_length=150)),
                ('student_class', models.CharField(blank=True, default='', help_text='e.g. "Class 10"', max_length=60)),
                ('section', models.CharField(blank=True, default='', max_length=30)),
                ('roll_number', models.CharField(blank=True, default='', max_length=30)),
                ('exam_name', models.CharField(blank=True, default='', help_text='e.g. "SSC" or "Annual Exam"', max_length=100)),
                ('result', models.CharField(blank=True, default='', help_text='e.g. "GPA 5.00" or "1st place"', max_length=100)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('achievement', models.CharField(blank=True, default='', help_text='e.g. "Talentpool scholarship" or "District champion".', max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='website/students/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Pinned to the front of the year.')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('student', models.ForeignKey(blank=True, help_text='Linked enrolment record, when the student is still on the roll.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='public_achievements', to='students.student')),
            ],
            options={
                'verbose_name': 'Successful student',
                'db_table': 'successful_students',
                'ordering': ['-academic_year', '-is_featured', 'order', 'full_name'],
            },
        ),
    ]
