# Generated by Django 5.2.8 on 2026-08-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name_en', models.CharField(max_length=200, verbose_name='Name (English)')),
                ('name_bn', models.CharField(blank=True, default='', max_length=200, verbose_name='Name (Bangla)')),
                ('short_name', models.CharField(blank=True, default='', max_length=100)),
                ('brand_name', models.CharField(blank=True, default='SmartSchool', help_text='Product wordmark shown beside the crest in the sidebar.', max_length=100)),
                ('village', models.CharField(blank=True, default='', max_length=100)),
                ('upazila', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('country', models.CharField(blank=True, default='Bangladesh', max_length=100)),
                ('established', models.CharField(blank=True, default='', max_length=20)),
                ('grade_range', models.CharField(blank=True, default='', max_length=150)),
                ('grade_range_bn', models.CharField(blank=True, default='', max_length=150)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, help_text='Square crest. Falls back to the built-in drawn logo when empty.', null=True, upload_to='school/')),
            ],
            options={
                'verbose_name': 'School profile',
                'verbose_name_plural': 'School profile',
                'db_table': 'school_profile',
            },
        ),
    ]
