# Generated by Django 5.2.8 on 2026-08-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('designation', models.CharField(default='Principal', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='principal/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='principal/signatures/')),
                ('qualification', models.CharField(blank=True, default='', max_length=255)),
                ('experience_years', models.PositiveSmallIntegerField(default=0)),
                ('message', models.TextField(blank=True, default='', help_text='Message from the principal, shown on the public site.')),
                ('biography', models.TextField(blank=True, default='')),
                ('tenure_start', models.DateField(blank=True, null=True)),
                ('tenure_end', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Principal',
                'db_table': 'principals',
                'ordering': ['-is_current', '-tenure_start'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('leave', 'Leave request'), ('expense', 'Expense approval'), ('result', 'Result publication'), ('admission', 'Admission approval'), ('event', 'Event approval'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='approvals/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.TextField(blank=True, default='')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'approval_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('audience', models.CharField(choices=[('all', 'Everyone'), ('staff', 'Staff only'), ('teachers', 'Teachers'), ('students', 'Students'), ('parents', 'Parents')], db_index=True, default='all', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notices/')),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notices',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
