# Generated by Django 5.2.8 on 2026-08-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('principal', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='Staff record, when the principal is also on the teaching roll.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_record', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='principal',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Linked login account for the principal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='principal_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
