# Generated by Django 5.2.8 on 2026-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['office', '-is_current', '-tenure_start'], 'verbose_name': 'Administrator', 'verbose_name_plural': 'Administration'},
        ),
        migrations.AddField(
            model_name='principal',
            name='office',
            field=models.CharField(choices=[('principal', 'Principal'), ('vice_principal', 'Vice Principal')], db_index=True, default='principal', help_text='Which seat this record holds.', max_length=20),
        ),
        migrations.AlterField(
            model_name='principal',
            name='designation',
            field=models.CharField(blank=True, default='', help_text='Free text, e.g. "Principal" or "Vice Principal".', max_length=100),
        ),
    ]
