# Generated by Django 5.2.8 on 2026-08-25 05:30

import apps.accounts.models.user_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('code', models.CharField(db_index=True, help_text="Dotted capability code, e.g. 'student.create'.", max_length=100, unique=True)),
                ('name', models.CharField(help_text="Human readable label, e.g. 'Create Students'.", max_length=150)),
                ('module', models.CharField(db_index=True, help_text="Resource family, e.g. 'student'.", max_length=50)),
                ('module_label', models.CharField(blank=True, default='', max_length=100)),
                ('action', models.CharField(help_text="Verb, e.g. 'view' | 'create' | 'update' | 'delete'.", max_length=50)),
                ('group', models.CharField(db_index=True, default='System', help_text="UI grouping, e.g. 'Academics' | 'Finance' | 'System'.", max_length=50)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'permissions',
                'ordering': ['group', 'module', 'action'],
                'indexes': [models.Index(fields=['module', 'action'], name='permissions_module_8c66f0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_system', models.BooleanField(default=False, help_text='System roles are seeded by the platform and cannot be renamed or deleted.')),
                ('permissions', models.ManyToManyField(blank=True, db_table='role_permissions', related_name='roles', to='accounts.permission')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email address')),
                ('username', models.CharField(db_index=True, max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=apps.accounts.models.user_model.profile_image_path)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('is_staff', models.BooleanField(default=False, help_text='Can sign in to the Django admin site.')),
                ('is_superuser', models.BooleanField(default=False, help_text='Bypasses every permission check.')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, help_text='The role this user inherits permissions from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', apps.accounts.models.user_model.UserManager()),
            ],
        ),
    ]
