# Generated by Django 5.2.8 on 2026-08-25 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('name', models.CharField(max_length=100)),
                ('name_bn', models.CharField(blank=True, default='', max_length=100)),
                ('code', models.CharField(help_text='e.g. "MATH-101"', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional'), ('extra', 'Extra-curricular')], default='compulsory', max_length=20)),
                ('full_marks', models.PositiveSmallIntegerField(default=100)),
                ('pass_marks', models.PositiveSmallIntegerField(default=33)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClassSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('weekly_periods', models.PositiveSmallIntegerField(default=5)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='classes.schoolclass')),
            ],
            options={
                'db_table': 'class_subjects',
                'ordering': ['school_class__order', 'subject__name'],
            },
        ),
    ]
