# Generated by Django 5.2.8 on 2026-08-25 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('full_name', models.CharField(max_length=150)),
                ('relation', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('brother', 'Brother'), ('sister', 'Sister'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], default='father', max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('alternate_phone', models.CharField(blank=True, default='', max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('occupation', models.CharField(blank=True, default='', max_length=100)),
                ('national_id', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardians',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('student_id', models.CharField(db_index=True, help_text='e.g. "THC-2026-0142"', max_length=30, unique=True)),
                ('admission_number', models.CharField(db_index=True, max_length=30, unique=True)),
                ('roll_number', models.PositiveIntegerField(blank=True, help_text='Roll within the section.', null=True)),
                ('full_name', models.CharField(db_index=True, max_length=150)),
                ('full_name_bn', models.CharField(blank=True, default='', max_length=150)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=10)),
                ('blood_group', models.CharField(blank=True, default='', max_length=5)),
                ('birth_certificate_no', models.CharField(blank=True, default='', max_length=40)),
                ('religion', models.CharField(blank=True, default='', max_length=40)),
                ('father_name', models.CharField(blank=True, default='', max_length=150)),
                ('mother_name', models.CharField(blank=True, default='', max_length=150)),
                ('emergency_contact', models.CharField(blank=True, default='', max_length=20)),
                ('admission_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('dropped', 'Dropped out'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20)),
                ('present_address', models.CharField(blank=True, default='', max_length=255)),
                ('permanent_address', models.CharField(blank=True, default='', max_length=255)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.guardian')),
                ('school_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='classes.schoolclass')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.section')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='classes.academicsession')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['school_class__order', 'section__name', 'roll_number', 'full_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('roll_number__isnull', False)), fields=('section', 'roll_number'), name='unique_roll_per_section')],
            },
        ),
    ]
